In [1]:
import random
import numpy as np

input_size = 2
hidden_size = 2 
num_classes = 2
learning_rate = 0.1  

Neuron_1 = 0.05
Neuron_2 = 0.1

Weight_input_hidden = np.random.uniform(0.0, 0.1, (hidden_size, input_size))
Weight_input_hidden = np.round(Weight_input_hidden, 3)

Weight_hidden_output = np.random.uniform(0.0, 0.1, (num_classes, hidden_size))
Weight_hidden_output = np.round(Weight_hidden_output, 3)

bias_1 = np.array([0.5, 0.5])
bias_2 = np.array([0.7, 0.7])

print(Weight_input_hidden)
print(Weight_hidden_output)

[[0.047 0.053]
 [0.056 0.005]]
[[0.025 0.024]
 [0.01  0.064]]


In [2]:
def net(inputs, weights, bias):
    net = np.dot(weights, inputs) + bias
    return net

In [3]:
def activation(net):
    return 2 / (1 + np.exp(-2 * net)) - 1

In [4]:
inputs = np.array([Neuron_1, Neuron_2])
hidden_net = net(inputs, Weight_input_hidden, bias_1)
hidden_outputs = activation(hidden_net)
print("Hidden layer outputs:", hidden_outputs)

Hidden layer outputs: [0.46811217 0.46470847]


In [5]:
output_net = net(hidden_outputs, Weight_hidden_output, bias_2)
outputs = activation(output_net)
print("Output layer outputs:", outputs)

Output layer outputs: [0.61867514 0.62576351]


In [6]:
target_output = np.array([0.01, 0.99])  

error_output = target_output - outputs  

derivative_output = 1 - outputs**2  
delta_output = error_output * derivative_output  
gradient_hidden_output = np.outer(delta_output, hidden_outputs)  

derivative_hidden = 1 - hidden_outputs**2  
delta_hidden = np.dot(Weight_hidden_output.T, delta_output) * derivative_hidden  
gradient_input_hidden = np.outer(delta_hidden, inputs)  

Weight_hidden_output += learning_rate * gradient_hidden_output  
Weight_hidden_output = np.round(Weight_hidden_output, 4)

Weight_input_hidden += learning_rate * gradient_input_hidden
Weight_input_hidden = np.round(Weight_input_hidden, 4)

# طباعة الأوزان بعد التحديث
print("Updated Weight_input_hidden:\n", Weight_input_hidden)
print("Updated Weight_hidden_output:\n", Weight_hidden_output)

Updated Weight_input_hidden:
 [[0.047  0.0529]
 [0.056  0.005 ]]
Updated Weight_hidden_output:
 [[0.0074 0.0065]
 [0.0204 0.0743]]
